-- 코드를 입력하세요
WITH A AS (SELECT CAR_ID, "대여중" AS AVAILIBILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= DATE('2022-10-16 00:00:00') AND END_DATE >=  DATE('2022-10-16 00:00:00'))

SELECT * FROM A

UNION

SELECT CAR_ID, "대여 가능" AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM A)

ORDER BY CAR_ID DESC;