SELECT CONCAT("/home/grep/src/", BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD  
LEFT JOIN USED_GOODS_FILE 
USING (BOARD_ID) 
WHERE VIEWS IN (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD);