WITH S AS (
    SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
)
SELECT BOOK.CATEGORY, SUM(S.SALES) AS TOTAL_SAELS
FROM BOOK
JOIN S
USING(BOOK_ID)
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;