With F AS (
    SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End' 
),
P AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'
),
C AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'
)

SELECT 
    CASE
        WHEN (SKILL_CODE & F.CODE) && (SKILL_CODE & P.CODE) THEN 'A'
        WHEN (SKILL_CODE & C.CODE) THEN 'B'
        WHEN (SKILL_CODE & F.CODE) THEN 'C'
    END AS GRADE,
    ID, EMAIL
FROM DEVELOPERS, F, P, C
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;